"use client";

import { useState } from "react";
import type { TaskDraftRow } from "@/lib/orchestration/types";

type FilterOption = "all" | "arrival" | "housekeeping_turn" | "stayover";

const FILTER_OPTIONS: { value: FilterOption; label: string }[] = [
  { value: "all", label: "All" },
  { value: "arrival", label: "Arrivals" },
  { value: "housekeeping_turn", label: "Departures" },
  { value: "stayover", label: "Stayovers" },
];

function formatDraftedAt(iso: string): string {
  return new Intl.DateTimeFormat("en-US", {
    timeZone: "America/Chicago",
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  }).format(new Date(iso));
}

function truncateId(id: string | null): string {
  if (!id) return "—";
  return id.slice(0, 8) + "…";
}

export default function DraftsTable({ drafts }: { drafts: TaskDraftRow[] }) {
  const [filter, setFilter] = useState<FilterOption>("all");

  const visible =
    filter === "all" ? drafts : drafts.filter((d) => d.card_type === filter);

  return (
    <main className="wrap--wide">
      <h1>Draft Review</h1>
      <p className="subtitle">
        Drafts generated by the orchestrator. Read-only — promote to tasks
        manually via Supabase when rules are validated.
      </p>

      <div className="admin-drafts__filter">
        <label htmlFor="drafts-filter" className="admin-drafts__filter-label">
          Filter:
        </label>
        <select
          id="drafts-filter"
          className="admin-drafts__filter-select"
          value={filter}
          onChange={(e) => setFilter(e.target.value as FilterOption)}
        >
          {FILTER_OPTIONS.map((opt) => (
            <option key={opt.value} value={opt.value}>
              {opt.label}
            </option>
          ))}
        </select>
        <span className="admin-drafts__filter-count">
          {visible.length} row{visible.length !== 1 ? "s" : ""}
        </span>
      </div>

      {visible.length === 0 ? (
        <p className="admin-drafts__empty">
          No drafts yet. The orchestrator will populate this when rules produce
          output.
        </p>
      ) : (
        <div className="admin-drafts__table-wrap">
          <table className="admin-drafts__table">
            <thead>
              <tr>
                <th>Drafted at</th>
                <th>Card type</th>
                <th>Title</th>
                <th>Priority</th>
                <th>Status</th>
                <th>Source event</th>
              </tr>
            </thead>
            <tbody>
              {visible.map((row) => (
                <tr key={row.id}>
                  <td className="admin-drafts__cell--mono">
                    {formatDraftedAt(row.drafted_at)}
                  </td>
                  <td>{row.card_type}</td>
                  <td>{row.title}</td>
                  <td>{row.priority}</td>
                  <td>{row.status}</td>
                  <td className="admin-drafts__cell--mono">
                    {truncateId(row.source_event_id)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </main>
  );
}
